const { createClient } = require('@supabase/supabase-js');
const { sendQuoteEmail } = require('../lib/email');
function parseCode(code){const m=String(code||'').toUpperCase().match(/^(Y\d{2}-\d{5})-([A-F0-9]{6})$/);return m?{quoteNumber:m[1],suffix:m[2]}:null}
async function findQuote(supabase,{token,code}){if(code){const p=parseCode(code);if(!p)return null;const {data}=await supabase.from('quotes').select('*').eq('quote_number',p.quoteNumber).like('short_token',p.suffix+'%').maybeSingle();return data||null}const {data}=await supabase.from('quotes').select('*').eq('public_token',token).maybeSingle();return data||null}
function isExpired(q){return q.valid_until&&q.valid_until<new Date().toISOString().slice(0,10)&&['sent','viewed'].includes(q.status)}
exports.handler=async(event)=>{try{
  const token=event.queryStringParameters?.token,code=event.queryStringParameters?.code;if(!token&&!code)return{statusCode:400,body:JSON.stringify({error:'Link inválido'})};
  const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SECRET_KEY);let q=await findQuote(supabase,{token,code});if(!q)return{statusCode:404,body:JSON.stringify({error:'Cotação não encontrada'})};
  if(q.status==='draft')return{statusCode:404,body:JSON.stringify({error:'Cotação ainda não enviada'})};
  if(q.status==='cancelled')return{statusCode:410,body:JSON.stringify({error:'Cotação indisponível'})};
  if(isExpired(q)){const expiredAt=new Date().toISOString();await supabase.from('quotes').update({status:'expired',expired_at:expiredAt}).eq('id',q.id);await supabase.from('quote_events').insert({quote_id:q.id,event_type:'expired',event_data:{valid_until:q.valid_until}});q={...q,status:'expired',expired_at:expiredAt}}
  const {data:items,error:itemErr}=await supabase.from('quote_items').select('id,position,description,quantity,unit_price,line_total,image_url,selected').eq('quote_id',q.id).order('position');if(itemErr)throw itemErr;
  let acceptance=null;if(q.status==='accepted'){const {data:a}=await supabase.from('quote_acceptances').select('approver_name,approver_role,approver_email,approver_phone,accepted_total,accepted_at,terms_version').eq('quote_id',q.id).order('accepted_at',{ascending:false}).limit(1).maybeSingle();acceptance=a||null}
  if(!q.first_viewed_at&&!['accepted','rejected','expired'].includes(q.status)){const viewedAt=new Date().toISOString();await supabase.from('quotes').update({first_viewed_at:viewedAt,status:q.status==='sent'?'viewed':q.status}).eq('id',q.id);await supabase.from('quote_events').insert({quote_id:q.id,event_type:'viewed'});q={...q,first_viewed_at:viewedAt,status:q.status==='sent'?'viewed':q.status};try{const r=await sendQuoteEmail(q,{headline:'Cotação visualizada',message:'O comprador abriu a cotação pela primeira vez.'});await supabase.from('quote_events').insert({quote_id:q.id,event_type:r.sent?'viewed_email_sent':'viewed_email_skipped',event_data:r})}catch(e){await supabase.from('quote_events').insert({quote_id:q.id,event_type:'viewed_email_failed',event_data:{error:e.message}})}}
  const publicQuote={id:q.id,quote_number:q.quote_number,status:q.status,quote_date:q.quote_date,client_id:q.client_id,company:q.company,cnpj:q.cnpj,address:q.address,phone:q.phone,tax:q.tax,other_amount:q.other_amount,freight:q.freight,delivery_terms:q.delivery_terms,delivery_address:q.delivery_address,seller:q.seller,payment_terms:q.payment_terms,notes:q.notes,subtotal:q.subtotal,total:q.total,valid_until:q.valid_until,terms_version:q.terms_version,terms_snapshot:q.terms_snapshot,first_viewed_at:q.first_viewed_at,accepted_at:q.accepted_at,rejected_at:q.rejected_at,rejection_reason:q.rejection_reason,expired_at:q.expired_at,items:items||[]};return{statusCode:200,headers:{'Content-Type':'application/json'},body:JSON.stringify({quote:publicQuote,acceptance})};
}catch(e){return{statusCode:500,headers:{'Content-Type':'application/json'},body:JSON.stringify({error:e.message||'Erro inesperado'})}}};
