const { getActor,canReadReports,canReadAllQuotes } = require('../lib/auth');
function json(statusCode,body){return{statusCode,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}}
function safeLike(v){return String(v||'').replace(/[,%()]/g,' ').trim()}
exports.handler=async(event)=>{try{
  if(event.httpMethod!=='GET')return json(405,{error:'Method not allowed'});
  const actor=await getActor(event);if(!actor)return json(401,{error:'Sessão inválida'});if(!canReadReports(actor))return json(403,{error:'Sem permissão para relatórios'});
  const {supabase,member,user}=actor,p=event.queryStringParameters||{};
  let q=supabase.from('quotes').select('id,quote_number,client_id,client_name,company,cnpj,quote_date,total,status,created_at,sent_at,first_viewed_at,accepted_at,rejected_at,expired_at,valid_until,quote_responsible,created_by,buyer_email_sent_at,buyer_email_delivered_at,buyer_email_opened_at,buyer_email_clicked_at,buyer_email_failed_at').order('created_at',{ascending:false}).limit(2000);
  if(!canReadAllQuotes(actor)&&member.role==='comercial')q=q.eq('created_by',user.id);
  if(p.from)q=q.gte('quote_date',p.from);if(p.to)q=q.lte('quote_date',p.to);if(p.responsible)q=q.eq('quote_responsible',p.responsible);if(p.status&&p.status!=='all')q=q.eq('status',p.status);if(p.created_by)q=q.eq('created_by',p.created_by);
  const search=safeLike(p.q);if(search)q=q.or(`quote_number.ilike.%${search}%,company.ilike.%${search}%,cnpj.ilike.%${search}%,client_id.ilike.%${search}%`);
  const {data:quotes,error}=await q;if(error)throw error;const rows=quotes||[];
  const nonDraft=rows.filter(x=>x.status!=='draft'),sent=nonDraft.filter(x=>x.sent_at),delivered=nonDraft.filter(x=>x.buyer_email_delivered_at),opened=nonDraft.filter(x=>x.buyer_email_opened_at),clicked=nonDraft.filter(x=>x.buyer_email_clicked_at),viewed=nonDraft.filter(x=>x.first_viewed_at),accepted=nonDraft.filter(x=>x.status==='accepted'),rejected=nonDraft.filter(x=>x.status==='rejected'),expired=nonDraft.filter(x=>x.status==='expired'),cancelled=nonDraft.filter(x=>x.status==='cancelled'),pending=nonDraft.filter(x=>['sent','viewed'].includes(x.status)),failed=nonDraft.filter(x=>x.buyer_email_failed_at);
  const rate=(n,d)=>d?Number((n/d*100).toFixed(2)):0,avg=pairs=>{const vals=pairs.map(([a,b])=>a&&b?(new Date(b)-new Date(a))/3600000:null).filter(v=>v!=null&&Number.isFinite(v)&&v>=0);return vals.length?Number((vals.reduce((s,v)=>s+v,0)/vals.length).toFixed(2)):0};
  const metrics={quotes:rows.length,finalized:nonDraft.length,quoted_value:rows.reduce((s,x)=>s+Number(x.total||0),0),accepted_value:accepted.reduce((s,x)=>s+Number(x.total||0),0),accepted:accepted.length,rejected:rejected.length,expired:expired.length,cancelled:cancelled.length,pending:pending.length,email_failed:failed.length,conversion_rate:rate(accepted.length,nonDraft.length),delivery_rate:rate(delivered.length,sent.length),open_rate:rate(opened.length,delivered.length||sent.length),click_rate:rate(clicked.length,opened.length||sent.length),view_rate:rate(viewed.length,nonDraft.length),conversion_after_view:rate(accepted.filter(x=>x.first_viewed_at).length,viewed.length),conversion_after_click:rate(accepted.filter(x=>x.buyer_email_clicked_at).length,clicked.length),avg_send_to_open_hours:avg(rows.map(x=>[x.buyer_email_sent_at||x.sent_at,x.buyer_email_opened_at])),avg_open_to_click_hours:avg(rows.map(x=>[x.buyer_email_opened_at,x.buyer_email_clicked_at])),avg_click_to_view_hours:avg(rows.map(x=>[x.buyer_email_clicked_at,x.first_viewed_at])),avg_open_to_view_hours:avg(rows.map(x=>[x.buyer_email_opened_at,x.first_viewed_at])),avg_view_to_accept_hours:avg(rows.map(x=>[x.first_viewed_at,x.accepted_at]))};
  const responsibleOptions=[...new Set(rows.map(x=>x.quote_responsible).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  let creatorOptions=[];if(member.role==='comercial'){creatorOptions=[{user_id:user.id,full_name:member.full_name||member.email,email:member.email}]}else{const ids=[...new Set(rows.map(x=>x.created_by).filter(Boolean))];if(ids.length){const {data:members}=await supabase.from('yepii_team_members').select('user_id,full_name,email').in('user_id',ids).eq('active',true);creatorOptions=(members||[]).sort((a,b)=>(a.full_name||a.email||'').localeCompare(b.full_name||b.email||'','pt-BR'))}}
  return json(200,{profile:member,metrics,responsible_options:responsibleOptions,creator_options:creatorOptions,quotes:rows});
}catch(e){return json(500,{error:e.message||'Erro inesperado'})}};
